project/project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
   path('admin/', admin.site.urls),
   # Делаем так, чтобы все адреса из нашего приложения (store/urls.py)
   # подключались к главному приложению с префиксом products/.
   path('products/', include('store.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/store/urls.py
from django.urls import path
from .views import (
    ProductsList, ProductDetail, ProductCreate, ProductUpdate, ProductDelete
)

urlpatterns = [
    path('', ProductsList.as_view(), name='product_list'),
    path('<int:pk>', ProductDetail.as_view(), name='product_detail'),
    path('create/', ProductCreate.as_view(), name='product_create'),
    path('<int:pk>/update/', ProductUpdate.as_view(), name='product_update'),
    path('<int:pk>/delete/', ProductDelete.as_view(), name='product_delete'),
]




project/store/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse


# Товар для нашей витрины
class Product(models.Model):
    name = models.CharField(
        max_length=50,
        unique=False,  # Название товароа не должны повторяться
    )
    discription = models.TextField(max_length=255)
    quanity = models.IntegerField(
        validators=[MinValueValidator(0)],
    )
    # Поле категории будет ссылаться на модель категории
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products',  # все продукты в категории будут доступны через поля products
    )
    price = models.FloatField(
        validators=[MinValueValidator(0.0)],
    )

    def __str__(self):
        return f'{self.name.title()}: {self.discription}'

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])




class Material(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ProductMaterial(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)




class Category(models.Model):
    # названия категорий тоже не должны повторяться
    name = models.CharField(max_length=100, unique=False)

    def __str__(self):
        return self.name.title()








project/store/forms.py
from django import forms
from .models import Product
from django.core.exceptions import ValidationError




class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        # fields = '__all__'
        # В место <__all__> мы могли бы перечислить все поля:

        fields = [
           'name',
           'discription',
           'quanity',
           'category',
           'price',
       ]



        # Но мы не стали так делать,
        # потому что метод __all__ Перебирает все поля модели

        '''
        Совет от автора
        
        Для рабочих проектов советуем всё-таки потратить время и перечислить поля, 
        чтобы не было ситуации, 
        что вы добавили новое поле в модель, 
        которое нельзя редактировать пользователям, 
        а из-за fields = ‘__all__’ это поле стало автоматически доступным для редактирования через форму. Примером такого поля может быть время создания товара. Странно, если пользователь будет иметь возможность его редактировать.
        В зависимости от того, 
        как мы расположим поля в списке, 
        в таком порядке они и будут выведены на странице. 
        Это значит, мы сможем удобнее и логичнее вывести данные для заполнения.
        '''
    # def clean(self):
    #     cleaned_data = super().clean()
    #     discription = cleaned_data.get('discription')
    #     if discription is not None and len(discription) < 20:
    #         raise ValidationError({
    #             'discription': 'Описание не может быть менее 20 символов.'
    #         })
    #
    #     name = cleaned_data.get("name")
    #     if name == discription:
    #         raise ValidationError(
    #             "Описание не должно быть идентичным названию."
    #         )
    #
    #     return cleaned_data

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")
        discription = cleaned_data.get("discription")

        if name == discription:
            raise ValidationError(
                "Описание не должно быть идентичным названию."
            )

        return cleaned_data

    ''' вот так мы можем проверить, написано ли название товара с заглавной буквы: '''
    def clean_name(self):
        name = self.cleaned_data['name']
        if name[0].islower():
            raise ValidationError(
                'Название должно начинаться с заглавной буквы.'
            )

        return name






project/store/views.py
# Импортируем класс, который говорит нам о том,
# что в этом представлении мы будем выводить список объектов из БД
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from .models import Product, Material, ProductMaterial
from .filters import ProductFilter
from .forms import ProductForm
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.utils.decorators import method_decorator
# from django.shortcuts import render, HttpResponseRedirect


class ProductsList(ListView):
    # Указываем модель, объекты которой мы будем выводить
    model = Product
    # Поле, которое будет использоваться для сортировки объектов
    ordering = 'name'
    # Указываем имя шаблона, в котором будут все инструкции о том,
    # как именно пользователю должны быть показаны наши объекты
    template_name = 'products.html'
    # Это имя списка, в котором будут лежать все объекты.
    # Его надо указать, чтобы обратиться к списку объектов в html-шаблоне.
    context_object_name = 'products'
    paginate_by = 2  # Вот так мы можем указать(ограничить) кол-во записей на странице

    # Переопределяем функцию получения списка товаров
    def get_queryset(self):
        # Получаем обычный запрос
        queryset = super().get_queryset()
        # Используем наш класс фильтрации.
        # self.request.GET содержит объект QueryDict, который мы рассматривали
        # в этом юните ранее.
        # Сохраняем нашу фильтрацию в объекте класса,
        # чтобы потом добавить в контекст и использовать в шаблоне.
        self.filterset = ProductFilter(self.request.GET, queryset)
        # Возвращаем из функции отфильтрованный список товаров
        return self.filterset.qs


    # # Вывод даты и времени
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class ProductDetail(DetailView):
    # Модель та же, но мы хотим получать информацию по отдельности
    model = Product
    # Используем другой шаблон product.html
    template_name = 'product.html'
    # Название обьекта, в которм будет выбранный пользователем продукт
    context_object_name = 'product'


# Добавляем новое представление для создания товаров
class ProductCreate(CreateView):
    # Указываем нашу разработанную форму
    form_class = ProductForm
    # Модель товаров
    model = Product
    # и новый шаблон, в котором используется форма.
    template_name = 'product_edit.html'


# Добавляем представление для изменения товара
class ProductUpdate(UpdateView):
    form_class = ProductForm
    model = Product
    template_name = 'product_edit.html'


# Представление удаляющее товар.
class ProductDelete(DeleteView):
    model = Product
    template_name = 'product_delete.html'
    success_url = reverse_lazy('product_list')


# Пример использование метод_декоратор, для предостовление сайта пользователю, при условий аунентификациий
# @method_decorator(login_required, name='dispatch')
# class ProtectedView(TemplateView):
#     template_name = 'prodected_page.html'


# Пример использований миксина LoginRequiredMixin ещё проще.
# Всего лишь необходимо добавить его в списке наследуемых классов при создании представления.
class ProtectedView(LoginRequiredMixin, TemplateView):
    template_name = 'prodected_page.html'










# Создание представления через функций(def, render, HttpsResponseRedirect)
# def create_product(request):
#     form = ProductForm()
#
#     if request.method == 'POST':
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('/products')
#
#
#     return render(request, 'product_edit.html', {'form': form})









project/store/templates/prodected_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

project/store/templates/product.html
{% extends 'store/default.html' %}

{% block title %}
Product
{% endblock %}

{% block content %}
<h1> Все товары </h1>
     <h2>{{product }}</h2>
{% endblock %}




project/store/templates/product_delete.html
{% extends 'store/default.html' %}


{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete"/>
</form>
{% endblock %}













project/store/templates/product_edit.html
{% extends 'store/default.html' %}


{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock %}













project/store/templates/products.html
{% extends 'store/default.html' %}
<!-- Фильтры -->
{% load custom_filters %}

<!-- Теги -->
{% load custom_tags %}

{% block title %}
Products
{% endblock title %}


{% block content %}
    <h1>Онлайн магазин</h1>
    <h3>Дата: {% time '%b %d %Y' %}</h3>
        <h1>Все товары</h1>

<!--        {# Добавляем форму, которая объединяет набор полей,-->
<!--        которые будут отправляться в запросе #}-->
        <form action="" method="get">
<!--            {# Переменная, которую мы передали через контекст,-->
<!--            может сгенерировать нам форму с полями #}-->
            {{ filterset.form.as_p }}
<!--            {# Добавим кнопку отправки данных формы #}-->
            <input type="submit" value="Поиск" />
        </form>


    <!--<h3>{{ time_now|date:'M d Y' }}</h3>-->
   <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }} </h3>

   <hr>
   {% if products %}
       <table>
           <tr>
               <td><h5> Название </h5></td>
          <td><h5> Описание </h5></td>
               <td><h5> Категория </h5></td>
               <td><h5> Цена </h5></td>
             <td><h5> Количество </h5></td>

           </tr>

           {% for product in products %}
           <tr>
               <td>{{ product.name }}</td>
               <td>{{ product.discription|truncatewords:2 }}</td>
               <td>{{ product.category.name }}</td>
               <!-- Используем наш фильтр -->
               <td>{{ product.price|currency:"usd" }}</td>
               <td>{{ product.quanity|my_filter }}</td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Товаров нет!</h2>
   {% endif %}

{# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

<!--        -->
<!--        <tr>-->
<!--    <th><label for="id_name">Name:</label></th>-->
<!--    <td>-->

<!--      <input type="text" name="name" value="test" maxlength="50" required id="id_name">-->


<!--    </td>-->
<!--  </tr>-->

<!--  <tr>-->
<!--    <th><label for="id_discription">Discription:</label></th>-->
<!--    <td>-->

<!--      <textarea name="discription" cols="40" rows="10" maxlength="255" required id="id_discription">-->
<!--test</textarea>-->
<!--        -->
<!--    </td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <th><label for="id_quanity">Quanity:</label></th>-->
<!--    <td>-->
<!--      <input type="number" name="quanity" value="1" required id="id_quanity">-->
<!--    </td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <th><label for="id_category">Category:</label></th>-->
<!--    <td>-->
<!--      <select name="category" required id="id_category">-->
<!--  <option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->
<!--  <option value="1" selected>Shoes</option>-->
<!--</select>-->
<!--    </td>-->
<!--  </tr>-->
<!--  <tr>-->
<!--    <th><label for="id_price">Price:</label></th>-->
<!--    <td>-->
<!--      <input type="number" name="price" value="42" step="any" required id="id_price">-->
<!--    </td>-->
<!--  </tr>-->
<!--    -->


{% endblock %}